name: Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Mengizinkan trigger build manual dari web

jobs:
  build:
    runs-on: ubuntu-latest # Menggunakan mesin virtual Linux terbaru

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # Mendapatkan kode dari repositori

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # Mengatasi masalah 'Permission denied'

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
